# Use root/example as user/password credentials
version: '3'

services:
  pokemon_wiki:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pokemon_database